### ISSUE TITLE
Raspi UnsatisfiedLinkError

### ISSUE THREAD

**Issue by meeximum** [yoctopuce/yoctolib_java#2]
Hi,

I'm getting following error
`
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.yoctopuce.YoctoAPI.YJniWrapper.reserveUSBAccess()V
	at com.yoctopuce.YoctoAPI.YJniWrapper.reserveUSBAccess(Native Method)
	at com.yoctopuce.YoctoAPI.YUSBHub.<init>(YUSBHub.java:104)
	at com.yoctopuce.YoctoAPI.YAPIContext._AddNewHub(YAPIContext.java:626)
	at com.yoctopuce.YoctoAPI.YAPIContext.RegisterHub(YAPIContext.java:937)
	at com.yoctopuce.YoctoAPI.YAPI.RegisterHub(YAPI.java:387)
	at Demo.main(Demo.java:8)
`

when running the Temperature Demo
`pi@baucam:~/yoctopuce/Examples/Doc-GettingStarted-Yocto-Temperature $ java -Djava.library.path=/home/pi/yoctopuce/Binaries -cp classes Demo`

In the Binaries directory is the one from your lib zip

I use latest download YoctoLib.java.31897.zip

regards
Meex

**Comment by meeximum** [comment]
Ok it seems to run via the VirtualHub, but not with direct USB connection?
On Windows 10 this is no problem, I can connect the sensor via USB, or is this because Windows automatically installs the Yoco drivers?

**Comment by yoctopuce** [comment]
If you want to use access USB device without using the VirtualHub you need to add the libyapi into you library path. I suspect that you have copied the wrong .so file or that the directory of the .so files are not your `java.library.path` property.

See our article on the subject: 
https://www.yoctopuce.com/EN/article/java-and-native-access-to-usb-ports

**Comment by meeximum** [comment]
I did exactly what is described in the article, in the path /home/pi/yoctopuce/Binaries everything is included *.so, it's exactly the content of the Binaries directory of your lib zip from your homepage

**Comment by yoctopuce** [comment]
Ok. I guess you are using a Raspberry Pi. Which distribution are you using?

Also could you dump the `java.library.path` at the start of your java code:
```
String libpath = System.getProperty("java.library.path");
System.out.println("java.library.path = " + libpath);
```
